package org.chelkatrao.bekki;

public enum AlphabetLatin {

    Yo("Yo", "Ё"),
    OO("O'", "Ў"),
    Ch("Ch", "Ч"),
    Sh("Sh", "Ш"),
    Yu("Yu", "Ю"),
    Ya("Ya", "Я"),
    ch("ch", "ч"),
    sh("sh", "ш"),
    yu("yu", "ю"),
    yo("yo", "ё"),
    Ye("Ye", "Е"),
    oo("o'", "ў"),
    GG("G'", "Ғ"),
    gg("g'", "ғ"),
    ya("ya", "я"),
    ee("e", "е"),
    y("y", "й"),
    Y("Y", "Й"),
    A("A", "А"),
    B("B", "Б"),
    V("V", "В"),
    G("G", "Г"),
    D("D", "Д"),
    J("J", "Ж"),
    Z("Z", "З"),
    I("I", "И"),
    K("K", "К"),
    L("L", "Л"),
    M("M", "М"),
    N("N", "Н"),
    O("O", "О"),
    P("P", "П"),
    R("R", "Р"),
    S("S", "С"),
    T("T", "Т"),
    U("U", "У"),
    F("F", "Ф"),
    X("X", "Х"),
    E("E", "Э"),
    a("a", "а"),
    b("b", "б"),
    v("v", "в"),
    g("g", "г"),
    d("d", "д"),
    j("j", "ж"),
    z("z", "з"),
    i("i", "и"),
    k("k", "к"),
    l("l", "л"),
    m("m", "м"),
    n("n", "н"),
    o("o", "о"),
    p("p", "п"),
    r("r", "р"),
    s("s", "с"),
    t("t", "т"),
    u("u", "у"),
    f("f", "ф"),
    x("x", "х"),
    e("e", "э"),
    Q("Q", "Қ"),
    q("q", "қ"),
    H("H", "Ҳ"),
    h("h", "ҳ"),
    tutuqBelgisi("'", "ъ");

    String key;
    String value;

    AlphabetLatin(String key, String value) {
        this.key = key;
        this.value = value;
    }
}
